apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana-server
  name: grafana-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: grafana-server
    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/mazza-geoffrey/front-regis/grafana:latest
          name: grafana-server
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "268435456"
      restartPolicy: Always

